# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfpwoZWmHm7dwdxOm-F_yK3JQbnoQCSP

#1. Find the number of siblings/spouses onboard for passengers who survived.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
train_df = pd.read_csv('train.csv')
survived_passengers = train_df[train_df['Survived'] == 1]
total_sibsp = survived_passengers['SibSp'].sum()
print(f"Total number of siblings/spouses onboard for passengers who survived: {total_sibsp}")

"""#2:Compare the survival rate for passengers who paid above and below the average fare."""

import pandas as pd


average_fare = train_df['Fare'].mean()

above_average = train_df[train_df['Fare'] > average_fare]
below_average = train_df[train_df['Fare'] <= average_fare]


survival_rate_above = above_average['Survived'].mean()
survival_rate_below = below_average['Survived'].mean()




print(f"Survival rate for passengers who paid above average fare: {survival_rate_above:.2f}")
print(f"Survival rate for passengers who paid below average fare: {survival_rate_below:.2f}")

"""#3:Plot a count plot for embarked showing passenger counts for each embarkation point"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='Embarked', data=train_df)


plt.xlabel("Embarkation Point")
plt.ylabel("Passenger Count")
plt.title("Passenger Counts for Each Embarkation Point")

plt.show()

"""# 4: Identify the age group with the highest survival rate."""

import pandas as pd


age_bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
age_labels = ['0-10', '10-20', '20-30', '30-40', '40-50', '50-60', '60-70', '70-80', '80-90']


train_df['AgeGroup'] = pd.cut(train_df['Age'], bins=age_bins, labels=age_labels, right=False)

age_group_survival = train_df.groupby('AgeGroup')['Survived'].mean()

"""#5: Create a pair plot for age, fare, and survived."""

import seaborn as sns
import matplotlib.pyplot as plt

cols = ['Age', 'Fare', 'Survived']


sns.pairplot(train_df[cols], hue='Survived')

plt.show()

"""#6:Determine if the fare is correlated with survival using a scatter plot."""

import seaborn as sns
import matplotlib.pyplot as plt


sns.scatterplot(x='Fare', y='Survived', data=train_df)


plt.xlabel("Fare")
plt.ylabel("Survived")
plt.title("Correlation between Fare and Survival")


plt.show()